### ISSUE TITLE
Add new port service to VIP that already exists without removing it first

### ISSUE THREAD

**Issue by alejandraklachquin** [globocom/GloboNetworkAPI-WebUI#17]
Today, if we want to add more services in a VIP (e.j.: we have a VIP that responds at port 80 and 443, and we want to add 1935 as well), we need to remove the VIPs we have configured for that IP in the equipments, edit the request form, and them create all services together. The ideal would be being able to add as much services as we want, without needing to delete existing services to a VIP.

**Comment by marcusgc** [comment]
closing issues already done long time ago...
